# Generated by Django 3.2.16 on 2024-05-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('dish_description', models.TextField(max_length=255, verbose_name='Описание блюда')),
                ('dish_calories', models.FloatField(verbose_name='Калорийность блюда')),
                ('dish_price', models.FloatField(verbose_name='Цена блюда')),
                ('valid_from_dttm', models.DateTimeField(verbose_name='Дата начала нахождения блюда в меню (datatime)')),
                ('valid_to_dttm', models.DateTimeField(verbose_name='Дата конца нахождения блюда в меню (datatime)')),
                ('SchoolWorkers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.schoolworkers', verbose_name='id работника учреждения, который выставил блюдо')),
            ],
            options={
                'verbose_name': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='DishTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishtypes_name', models.CharField(max_length=255, verbose_name='Прием пищи')),
            ],
            options={
                'verbose_name': 'Тип блюда, когда он принимается (завтрак, обед или ужин)',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_mark', models.IntegerField(verbose_name='Оценка отзыва')),
                ('reviews_text', models.TextField(verbose_name='Текст отзыва')),
                ('dishes_id', models.IntegerField(verbose_name='id блюда')),
                ('reviews_created_dttm', models.DateTimeField(verbose_name='Дата создания отзыва')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parents', verbose_name='Оценка отзыва')),
            ],
            options={
                'verbose_name': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_created_dttm', models.DateTimeField(verbose_name='Дата создания заказа (datatime)')),
                ('orders_day_dt', models.DateField(verbose_name='Дата, на которую создан заказ')),
                ('orders_if_paid', models.BooleanField(verbose_name='Флаг, оплачен или нет')),
                ('orders_payment_amount', models.FloatField(verbose_name='Стоимость заказа (вычислимое поля)')),
                ('children_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.children', verbose_name='id ребенка, на которого заказано блюдо')),
            ],
            options={
                'verbose_name': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='DishesInOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dishes')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.orders')),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='dish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dishtypes', verbose_name='Тип блюда (завтрак, обед или ужин)'),
        ),
    ]
