# Generated by Django 3.2.16 on 2024-05-12 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('dishes_description', models.TextField(max_length=1023, verbose_name='Описание блюда')),
                ('dishes_calories', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(750)], verbose_name='Калорийность блюда')),
                ('dishes_price', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Цена блюда')),
                ('valid_from_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала нахождения блюда в меню (datatime)')),
                ('valid_to_dttm', models.DateTimeField(verbose_name='Дата конца нахождения блюда в меню (datatime)')),
                ('SchoolWorkers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.schoolworkers', verbose_name='id работника учреждения, который выставил блюдо')),
            ],
            options={
                'verbose_name': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='DishesInOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dishes')),
            ],
        ),
        migrations.CreateModel(
            name='DishTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_types_name', models.CharField(default='Завтрак', max_length=255, verbose_name='Прием пищи')),
            ],
            options={
                'verbose_name': 'Тип блюда, когда он принимается (завтрак, обед или ужин)',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_mark', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка отзыва')),
                ('reviews_text', models.TextField(max_length=1023, verbose_name='Текст отзыва')),
                ('reviews_created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва')),
                ('dishes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dishes', verbose_name='id блюда')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parents', verbose_name='Оценка отзыва')),
            ],
            options={
                'verbose_name': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа (datatime)')),
                ('orders_day_dt', models.DateField(verbose_name='Дата, на которую создан заказ')),
                ('orders_if_paid', models.BooleanField(default=False, verbose_name='Флаг, оплачен или нет')),
                ('orders_payment_amount', models.FloatField(default=200, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость заказа (вычислимое поля)')),
                ('children_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.children', verbose_name='id ребенка, на которого заказано блюдо')),
                ('orders_dishes', models.ManyToManyField(through='food.DishesInOrders', to='food.Dishes', verbose_name='Список блюд')),
            ],
            options={
                'verbose_name': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='dishesinorders',
            name='orders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.orders'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='dishes_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dishtypes', verbose_name='Тип блюда (завтрак, обед или ужин)'),
        ),
    ]
