# Generated by Django 3.2.16 on 2024-05-17 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks_created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания чека (datatime)')),
                ('checks_payment_amount', models.FloatField(default=200, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость чека (вычислимое поля)')),
            ],
            options={
                'verbose_name': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrdersInChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.checks')),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.orders')),
            ],
        ),
        migrations.AddField(
            model_name='checks',
            name='orders_id',
            field=models.ManyToManyField(through='food.OrdersInChecks', to='food.Orders', verbose_name='Список заказов'),
        ),
    ]
