# Generated by Django 3.2.16 on 2024-05-17 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20240518_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checks',
            options={'verbose_name': 'Checks'},
        ),
        migrations.RemoveField(
            model_name='checks',
            name='orders_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orders_payment_amount',
        ),
        migrations.AddField(
            model_name='checks',
            name='checks_dishes',
            field=models.ManyToManyField(through='food.OrdersInChecks', to='food.Orders', verbose_name='Список заказов'),
        ),
        migrations.AddField(
            model_name='orders',
            name='orders_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость заказа (вычислимое поля)'),
        ),
    ]
