# Generated by Django 3.2.16 on 2024-05-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20240518_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checks',
            old_name='checks_dishes',
            new_name='orders_list',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='orders_dishes',
            new_name='dishes_list',
        ),
    ]
