# Generated by Django 3.2.16 on 2024-05-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20240518_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checks',
            old_name='checks_payment_amount',
            new_name='checks_price',
        ),
    ]
