# Generated by Django 3.2.16 on 2024-06-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20240629_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='checks_children',
            field=models.IntegerField(verbose_name='Количество детей'),
        ),
    ]
