# Generated by Django 3.2.16 on 2024-06-29 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_checks_checks_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checks',
            name='order_list',
        ),
        migrations.AddField(
            model_name='checks',
            name='orders_list_str',
            field=models.TextField(default='', verbose_name='Список заказов в виде строки'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='checks_children',
            field=models.IntegerField(verbose_name='ID ребенка'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='checks_created_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания чека (datetime)'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='checks_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость чека (вычислимое поле)'),
        ),
    ]
