# Generated by Django 3.2.16 on 2024-06-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20240629_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='orders_list_str',
            field=models.TextField(verbose_name='Список заказов в виде строки'),
        ),
    ]
