# Generated by Django 3.2.16 on 2024-05-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrators_login', models.CharField(max_length=31, verbose_name='Логин администратора')),
                ('administrators_password', models.CharField(max_length=31, verbose_name='Пароль администратора')),
            ],
            options={
                'verbose_name': 'Администратор',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_number', models.IntegerField(max_length=31, verbose_name='Номер банковской карты')),
                ('cards_cvv', models.IntegerField(max_length=31, verbose_name='Логин администратора')),
                ('cards_expiry', models.CharField(max_length=31, verbose_name='Логин администратора')),
            ],
            options={
                'verbose_name': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='SchoolWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolworkers_login', models.CharField(max_length=31, verbose_name='Логин работника учреждения')),
                ('schoolworkers_password', models.CharField(max_length=31, verbose_name='Пароль работника учреждения')),
                ('administrators_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.administrators', verbose_name='id администратора, заносившего пользователя')),
            ],
            options={
                'verbose_name': 'Работники школы',
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_login', models.CharField(max_length=31, verbose_name='Логин родителя')),
                ('parents_name', models.CharField(max_length=31, verbose_name='Имя родителя')),
                ('parents_password', models.CharField(max_length=31, verbose_name='Пароль родителя')),
                ('administrators_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.administrators', verbose_name='id администратора, заносившего пользователя')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cards', verbose_name='Номер карты родителя родителя')),
            ],
            options={
                'verbose_name': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_name', models.CharField(max_length=31, verbose_name='Имя ребенка')),
                ('parents_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parents')),
            ],
            options={
                'verbose_name': 'Дети',
            },
        ),
    ]
