# Generated by Django 3.2.16 on 2024-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240525_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='children_surname',
            field=models.CharField(max_length=31, null=True, verbose_name='Фамилия ребенка'),
        ),
    ]
