# Generated by Django 3.2.16 on 2024-05-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240529_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='parents_surname',
            field=models.CharField(default='НЕТ', max_length=31, verbose_name='Фамилия родителя'),
        ),
    ]
